[project]
name = "spotter-sd-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cyclopts>=3.14.2",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "scipy>=1.13.1",
]

[project.scripts]
spotter-sd-parser = "spotter_sd_parser.sd_file_parser:app"
spotter-smartmooring-parser = "spotter_sd_parser.smartmooring:app"
spotter-location-parser = "spotter_sd_parser.location_pd:app"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.36.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
